#enrollment-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: backend
spec:
  selector:
    app: enrollment-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
