#study-plan-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: study-plan-service
  namespace: backend
spec:
  selector:
    app: study-plan-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
