#timetable-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: timetable-service
  namespace: backend
spec:
  selector:
    app: timetable-service
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
