#ps-frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ps-frontend-service
  namespace: frontend
spec:
  selector:
    app: ps-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer