#pp-frontend-service-monitoring.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pp-frontend
  labels:
    team: frontend
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: pp-frontend
  endpoints:
    - port: 80