#ps-frontend-service-monitoring.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ps-frontend
  labels:
    team: frontend
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: ps-frontend
  endpoints:
    - port: 80