#index-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-service-deployment
  namespace: backend
  labels:
    app: index-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: index-service
  template:
    metadata:
      labels:
        app: index-service
    spec:
      containers:
        - name: index-service
          image: kisiel75311/timetable_service:1706842257
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-database
            - name: STUDY_PLAN_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: study_plan_service_host
            - name: STUDY_PLAN_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: study_plan_service_port
            - name: TIMETABLE_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: timetable_service_host
            - name: TIMETABLE_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: timetable_service_port
            - name: ENROLLMENT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: enrollment_service_host
            - name: ENROLLMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: enrollment_service_port
            - name: INDEX_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: index_service_host
            - name: INDEX_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: index_service_port
            - name: ACCOUNT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: account_service_host
            - name: ACCOUNT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: account_service_port