#study-plan-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-plan-service-deployment
  namespace: backend
  labels:
    app: study-plan-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: study-plan-service
  template:
    metadata:
      labels:
        app: study-plan-service
    spec:
      containers:
        - name: study-plan-service
          image: kisiel75311/study_plan_service:v1.2 #change this to your own image
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-database