#backend-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: backend
data:
  db_host: "mariadb-service.database.svc.cluster.local"
  db_port: "3306"
  study_plan_service_host: "study-plan-service.backend.svc.cluster.local"
  study_plan_service_port: "8080"
